### PR TITLE
React 15

### PR DESCRIPTION
**Pull request by lemieux**
While digging a bit to optimize the widget, I went for a React upgrade. Seems pretty straightforward and after playing with the widget a bit it seems pretty stable. Might be good to smoke test the widget a bit before releasing this.

@Mario54 @mspensieri @dannytranlx @jugarrit @alavers @chloepouprom @liyefei737

### CODE REVIEW

**Comment by mspensieri** [comment]
👍

**Comment by chloepouprom** [comment]
👍

**Comment by dannytranlx** [comment]
👍

**Comment by alavers** [comment]
👍

**Comment by liyefei737** [comment]
👍

**Comment by alavers** [comment]
@lemieux can you fill this trello card out? https://trello.com/c/8XmTBBHa/4051-bug-bash-react-15

**Pull request merged**
