### PR TITLE
Fix widget animations

### PR DESCRIPTION
**Pull request by chloepouprom**
@lemieux @alavers @dannytranlx

### CODE REVIEW

**Comment by lemieux** [comment]
`sk-close-frames-md` doesn't exist?

**Comment by chloepouprom** [comment]
No, it doesn't.

Although, maybe to avoid confusion, it might be worth it to have `sk-close-frames-md` instead of `sk-close-frames`

**Comment by lemieux** [comment]
much clearer :ok_hand: :+1:

**Comment by alavers** [comment]
👍

**Pull request merged**
