### PR TITLE
Set error for SMS linking from config, use retry-after

### PR DESCRIPTION
**Pull request by jugarrit**
@chloepouprom @lemieux @dannytranlx @mspensieri 

Error was hardcoded previously, now using config values.
Also making use of retry-after returned from server.

### CODE REVIEW

**Comment by chloepouprom** [comment]
Oops, I think I missed those during rebase. 👍

**Comment by mspensieri** [comment]
👍

**Comment by lemieux** [comment]
:+1:

**Comment by dannytranlx** [comment]
👍

**Pull request merged**
