### PR TITLE
Add error banner for offline messagess

### PR DESCRIPTION
**Pull request by liyefei737**
Add a catch to capture offline error, show banner and delete the message.
@lemieux @mspensieri @chloepouprom @jugarrit

### CODE REVIEW

**Comment by liyefei737** [comment]
image

**Comment by lemieux** [comment]
:+1:

**Comment by chloepouprom** [comment]
👍

**Comment by dannytranlx** [comment]
👍

**Comment by jugarrit** [comment]
EZPZ

**Pull request merged**
