### PR TITLE
New message sound notification

### PR DESCRIPTION
**Pull request by lemieux**
Second part of new message notification : sound.

This would play a sound notification when the a new message comes in and the page in now in focus.

I also improve the way we clear the unread notification. It now clears whenever you click, mousewheel, or touch the widget.

@mspensieri @dannytranlx @Mario54

### CODE REVIEW

**Comment by mspensieri** [comment]
:+1: The mp3 will be hosted on cdn right?

**Comment by lemieux** [comment]
Yup, that reminds me to add the file to the uploaded file list...

**Comment by dannytranlx** [comment]
Do we expose the file path? It would be nice to let the users use their own sound file 😂

**Comment by lemieux** [comment]
Nope, and, nope.

**Pull request merged**
