### PR TITLE
Reduce flag size

### PR DESCRIPTION
**Pull request by jugarrit**

### CODE REVIEW

**Comment by mspensieri** [comment]
This is actually changing the resolution of the image, won't we lose quality?

**Comment by jugarrit** [comment]
@mspensieri absolutely, yes. The image size was far too large, however...
Kevin provided the shrunk image.

**Comment by lemieux** [comment]
The image file was like 280kb... it was non-sense.

Did you test if was still working? My fear with resizing the image was that the CSS wouldn't be aligned correctly anymore.

**Comment by lemieux** [comment]
This https://github.com/smooch/smooch-js/blob/integration/src/stylesheets/flags.less

**Comment by jugarrit** [comment]
Of course I tested it!
I wanted the code to be easily adjustable, and it seems that it was.

**Pull request merged**
