### PR TITLE
UI Polishing

### PR DESCRIPTION
**Pull request by lemieux**
Some polish fixes after a pass with the all mighty designer.

@mspensieri @dannytranlx @jugarrit @chloepouprom

### CODE REVIEW

**Comment by chloepouprom** [comment]
Screenshots? 😄

**Comment by mspensieri** [comment]
👍

**Comment by lemieux** [comment]
@chloepouprom highlights are : no rounded corners when mobile, I remove an old icon that was still in the code for some reason, I slightly adjust the vertical alignment of text in the header and I tweaked the open/close animation of the widget in badge mode.

I could make a screen shot but the only thing you might really see is the disappearance of rounded corners.

**Comment by chloepouprom** [comment]
👍

**Pull request merged**
