### PR TITLE
Fix unread badge overlap

### PR DESCRIPTION
**Pull request by lemieux**
Just reordered the component to make sure the unread badge appears on top of the icon
image

@alavers @mspensieri @Mario54 @jpjoyal @jugarrit @dannytranlx

### CODE REVIEW

**Comment by mspensieri** [comment]
👍

**Comment by jugarrit** [comment]
http://i.imgur.com/TnQRX6v.gif

**Comment by jugarrit** [comment]
tnqrx6v

**Comment by jugarrit** [comment]
👍

**Comment by alavers** [comment]
lol 👍 

🍌

**Pull request merged**
